// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudUghUesbV8CSzZc4Sofa-aNf4-JsmFI',
    appId: '1:824733657707:web:eb90f37410b9043457df2e',
    messagingSenderId: '824733657707',
    projectId: 'grow-duino',
    authDomain: 'grow-duino.firebaseapp.com',
    storageBucket: 'grow-duino.appspot.com',
    measurementId: 'G-T75WD4ZJY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMiI3R9QkOtEkn4oka52pRu6P3J3NCqA',
    appId: '1:824733657707:android:8abe724885c83b0f57df2e',
    messagingSenderId: '824733657707',
    projectId: 'grow-duino',
    storageBucket: 'grow-duino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JVJqhaFGsv93EL0NL6PISd73rNlt3yU',
    appId: '1:824733657707:ios:4941112c643b9eee57df2e',
    messagingSenderId: '824733657707',
    projectId: 'grow-duino',
    storageBucket: 'grow-duino.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1JVJqhaFGsv93EL0NL6PISd73rNlt3yU',
    appId: '1:824733657707:ios:17e4ef1bc75cbdbe57df2e',
    messagingSenderId: '824733657707',
    projectId: 'grow-duino',
    storageBucket: 'grow-duino.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo.RunnerTests',
  );
}
